/*
 CIAccordionFoldTransition
 CIBarsSwipeTransition
 CICopyMachineTransition
 CIDisintegrateWithMaskTransition
 CIDissolveTransition
 CIFlashTransition
 CIModTransition
 CIPageCurlTransition
 CIPageCurlWithShadowTransition
 CIRippleTransition
 CISwipeTransition
 */
